services:
  training_ad_detection_mri_streaming_data:
    build:
      context: ../..
      dockerfile: infrastructure/docker/alzheimer_detection_training
    # depends_on:
    #   - db_AD
    command: 
      - "python"
      - "src/scripts/alzheimer_detection_streaming_data_training.py"
      - "--data"
      - "${DATASET_STORAGE_CONNECTION_STRING}"
      - "--checkpoint"
      - "${CHECKPOINT_STORAGE_CONNECTION_STRING}"
      - "--model"
      - "${MODEL_STORAGE_CONNECTION_STRING}"
    environment:
      TRAIN_DATA_DIR: "Oasis1"
      TRAIN_DATA_LABELS: "demented,nondemented"
      MODELS_REPO_DIR_PATH: "models"
      CHECKPOINT_REPO_DIR_PATH: "checkpoints"
      MODELS_PERF_REPO_DIR_PATH: "metrics"
      DATASET_STORAGE_CONNECTION_STRING: ${DATASET_STORAGE_CONNECTION_STRING}
      CHECKPOINT_STORAGE_CONNECTION_STRING: ${CHECKPOINT_STORAGE_CONNECTION_STRING}
      MODEL_STORAGE_CONNECTION_STRING: ${MODEL_STORAGE_CONNECTION_STRING}