services:
  training_ad_detection_mri:
    build:
      context: ../..
      dockerfile: infrastructure/docker/alzheimer_detection_training
    # depends_on:
    #   - db_AD
    command: 
      - "python"
      - "src/scripts/alzheimer_detection_static_data_training.py"
      - "--data"
      - "${DATASET_STORAGE_CONNECTION_STRING}"
      - "--checkpoint"
      - "${CHECKPOINT_STORAGE_CONNECTION_STRING}"
      - "--model"
      - "${MODEL_STORAGE_CONNECTION_STRING}"
    environment:
      DATASET_STORAGE_CONNECTION_STRING: ${DATASET_STORAGE_CONNECTION_STRING}
      CHECKPOINT_STORAGE_CONNECTION_STRING: ${CHECKPOINT_STORAGE_CONNECTION_STRING}
      MODEL_STORAGE_CONNECTION_STRING: ${MODEL_STORAGE_CONNECTION_STRING}