class VariableNames:
    ROOT_DIR="ROOT_DIR"
    MODELS_REPO_DIR_PATH="MODELS_REPO_DIR_PATH"
    BASE_MODEL_NAME="BASE_MODEL_NAME"
    BASE_MODEL_PATH="BASE_MODEL_PATH"
    TRAIN_DATA_DIR="TRAIN_DATA_DIR"
    S3_BUCKET_NAME="S3_BUCKET_NAME"
